name: Баг
description: Описание проблемы или бага в игре.
labels: ["тип: ошибка", ""]
title: "Отчет об баге: "
body:
  - type: dropdown
    attributes:
      label: Платформа
      description: На какой платформе ты играешь?
      options:
        - Android
        - iOS/iPadOS
        - Windows
        - Скомпилировал игру из исходного кода
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Опишите свой баг."

  - type: textarea
    attributes:
      label: Описание (можно вставить изображения или видео с записанными ощибками)
      description: Расскажите как можно подробнее.
      placeholder: Опиши проблему здесь...
    validations:
      required: true
